services:
 
  db:
    image: mysql:8.2
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
     - "3306:3306"
    expose:
     - "3306"

  web:
    build:
      context: ./Dockerfile
      dockerfile: dockerfile.yml
    ports:
      - "80:80"
    expose:
      - "80"
    volumes: 
      - ./src:/var/www/html
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: test



volumes:
  data:



