version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql
    networks:
      - mynetwork
  web:
    build:
      context: ./Dockerfile
      dockerfile: dockerfile.yml
    ports:
      - "80:80"
    expose:
      - "80"
    volumes: 
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: test
    networks:
      - mynetwork
# Names our volume
volumes:
  data:
networks:
  mynetwork:
    driver: host
