version: '3'

services:

  db:
    image: mysql:8.2
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  web:
    build: ./Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    volumes: 
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: test

volumes:
  data:



