version: '3'

services:

  db:
    image: mysql:8.2
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"

  web:
    build: ./php
    ports:
      - "8080:80"
    volumes: 
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: test

volumes:
  data:



FROM php:7.4-fpm
RUN docker-php-ext-install pdo pdo_mysql
